name: 'be-a11y Accessibility Checker'
description: 'Automated accessibility checks for HTML or URLs with be-a11y.'
author: 'be-lenka'
inputs:
  url:
    description: 'URL or directory to analyze (e.g. https://example.com or ./public)'
    required: true
  report:
    description: 'Optional path for JSON report output (e.g. report.json)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Run be-a11y accessibility checker
      run: |
        ls -la
        echo "Running be-a11y on URL: ${{ inputs.url }}"
        echo "Report path: ${{ inputs.report }}"
        npm install
        npm run build
        if [ -z "${{ inputs.report }}" ]; then
          node dist/index.js "${{ inputs.url }}"
        else
          node dist/index.js "${{ inputs.url }}" "${{ inputs.report }}"
        fi
      shell: bash
branding:
  icon: 'check-circle'
  color: 'purple'