name: 'be-a11y Accessibility Checker'
description: 'Automated accessibility checks for HTML or URLs with be-a11y.'
author: 'be-lenka'
inputs:
  url:
    description: 'URL or directory to analyze (e.g. https://example.com or ./public)'
    required: true
  report:
    description: 'Optional path for JSON report output (e.g. report.json)'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'check-circle'
  color: 'purple'
