name: Run be-a11y Accessibility Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run be-a11y on URL
        uses: ./ # or be-lenka/be-a11y@main po merge
        with:
          url: 'https://example.com'
      # - name: Run be-a11y with JSON export
      #   uses: ./
      #   with:
      #     url: 'https://example.com'
      #     report: 'a11y-report.json'